name: Build and push Docker image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Decode SSH key
        id: decode_ssh_key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > id_rsa
          echo "PRIVATE_KEY=$(cat id_rsa)" >> $GITHUB_ENV
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ env.PRIVATE_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/prod/Dockerfile
          push: true
          tags: hanschrome/solidjobs-web:latest
          args: |
            --build-arg SSH_PRIVATE_KEY="${{ steps.decode_ssh_key.outputs.private_key }}"
